# (C) 2019 The Johns Hopkins University Applied Physics Laboratory LLC.
version: "3"

services:

  backend:
    environment:
      - AUTH_MODULE=${AUTH_MODULE}
      - VEGAS_CLIENT_SECRET
      - EVE_SERVER=http://eve:${EVE_PORT}
      - REDIS_SERVER=redis
      - PINE_LOGGING_CONFIG_FILE=${PINE_LOGGING_CONFIG_FILE:-/nlp-web-app/shared/logging.python.dev.json}

  eve:
    build:
      args:
        - DB_DIR=/nlp-web-app/eve/db
        - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ${EVE_DB_VOLUME}:/nlp-web-app/eve/db
    environment:
      - MONGO_URI=
      - PINE_LOGGING_CONFIG_FILE=${PINE_LOGGING_CONFIG_FILE:-/nlp-web-app/shared/logging.python.dev.json}

  frontend_annotation:
    build:
      args:
        - SERVER_TYPE=${EXPOSED_SERVER_TYPE}
    ports:
      - "${EXPOSED_PORT}:443"
    environment:
      - BACKEND_SERVER=http://backend:${BACKEND_PORT}
      - SERVER_NAME=${EXPOSED_SERVER_NAME}

volumes:
  eve_db:
