# (C) 2019 The Johns Hopkins University Applied Physics Laboratory LLC.
version: "3"

services:

  backend:
    environment:
      - VEGAS_CLIENT_SECRET
      - EVE_SERVER=http://eve:7510
      - REDIS_SERVER=redis
      - PINE_LOGGING_CONFIG_FILE=/nlp-web-app/shared/logging.python.dev.json

  eve:
    build:
      args:
        - DB_DIR=/nlp-web-app/eve/db
    volumes:
      - eve_db:/nlp-web-app/eve/db
    environment:
      - MONGO_URI=
      - PINE_LOGGING_CONFIG_FILE=/nlp-web-app/shared/logging.python.dev.json

  frontend_annotation:
    build:
      args:
        - SERVER_TYPE=${EXPOSED_SERVER_TYPE}
    ports:
      - "${EXPOSED_PORT}:443"
    environment:
      - BACKEND_SERVER=http://backend:${BACKEND_PORT}
      - SERVER_NAME=${EXPOSED_SERVER_NAME}

volumes:
  eve_db:
