# (C) 2019 The Johns Hopkins University Applied Physics Laboratory LLC.
{{- $component := .Values.backend }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pine-chart.fullname" . }}-{{ $component.name }}
  labels:
    name: {{ template "pine-chart.name" . }}
    component: {{ $component.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with $component.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ $component.service.type }}
  ports:
    - port: {{ $component.service.port }}
      targetPort: {{ $component.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "pine-chart.name" . }}
    component: {{ $component.name }}
    release: {{ .Release.Name }}
