# (C) 2019 The Johns Hopkins University Applied Physics Laboratory LLC.
{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "pine-chart.fullname" . -}}
{{- $frontendComponentName := .Values.ingress.frontend.name -}}
{{- $frontendComponentPort := .Values.ingress.frontend.port -}}
{{- $frontendComponentPath := .Values.ingress.frontend.path -}}
{{- $backendComponentName := .Values.ingress.backend.name -}}
{{- $backendComponentPort := .Values.ingress.backend.port -}}
{{- $backendComponentPath := .Values.ingress.backend.path }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    chart: {{ template "pine-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $backendComponentPath }}/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $backendComponentName }}
                port:
                  number: {{ $backendComponentPort }}
          - path: {{ $frontendComponentPath }}(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ $frontendComponentName }}
                port:
                  number: {{ $frontendComponentPort }}
  {{- end }}
{{- end }}
