# (C) 2019 The Johns Hopkins University Applied Physics Laboratory LLC.
{{- $root := . }}
{{- range $name, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pine-chart.fullname" $root }}-{{ $name }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}
